version: '2'
volumes: 
  dashboard-data:
  speedtest-data:
services:
  logging:
    build: ./logging
    privileged: true
    restart: always
    network_mode: host
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1