FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:latest-run
WORKDIR /app

RUN install_packages \
    py3-gobject3 \
    py3-pydbus \
    py3-requests


COPY entrypoint.sh /app/
COPY run.py /app/

ENTRYPOINT [ "/bin/bash" ]
CMD ["entrypoint.sh"]
